title: Bruno Verussa # your name (or website title) here
logo: "/images/me.png?raw=true" # your photo (or logo) here
theme: jekyll-theme-minimal
google_analytics: UA-160742497-1 # Google Analytics tracking ID here: eg. UA-000000-0
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am passionate about technology and how to use it to improve peopleâ€™s quality of life. 
  <br><br>
  ğŸ‡§ğŸ‡·ğŸ‡¨ğŸ‡¦
  <br><br>
  Please contact me with any questions: b.verussa@gmail.com
  <br><br>
  <a href="https://www.linkedin.com/in/bverussa/">View My LinkedIn Profile</a> 
